---
- name: Install wpasupplicant packages
  apt:
    name="{{ pkgs }}"
    state="present"
    update_cache=False
    install_recommends=False
  vars:
    pkgs:
    - wpasupplicant

- name: wpa supplicant conf
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0600

